### ISSUE TITLE
Is it necessary to format the data?

### ISSUE THREAD

**Issue by SakuraKyuo** [wuxianlin/oneplus12_pvmfw#2]
First of all, thank you for your contribution. At the same time, I would like to ask: I saw `fastboot -w` mentioned in the Readme. Is it necessary to format the data?

**Comment by MlgmXyysd** [comment]
is necessary if you changed pvmfw (flash or erase), otherwise it will reboot to Recovery (FBE decryption failed)

**Comment by SakuraKyuo** [comment]
thx for answer, btw is it possible to port for Android14? (I mean will it works on Android 14 or not)

**Comment by SakuraKyuo** [comment]
thx for answer, btw is it possible to port for Android14? (I mean will it works on Android 14 or not)

**Comment by MlgmXyysd** [comment]
We don't know. pvmfw image is extracted from Android 15, we don't see OEM compiled this image in Android 14.
